### ISSUE TITLE
[BUG] 4 rank LJ runs fail with "lost atoms" error on recent tags of LAMMPS

### ISSUE THREAD

**Issue by IanBogle** [lammps/lammps#3926]
**Summary**
Running LJ on 4 GPUs on `stable_2Aug2023` or `patch_15Jun2023` results in a runtime error that reports "lost atoms".

**LAMMPS Version and Platform**
Running on ROCm, any version from 5.4.6 to 5.6.1, any tag of LAMMPS  `patch_15Jun2023` or more recent

**Expected Behavior**
Atoms should not be lost, and the 4 rank run should complete successfully, as in patch `stable_23Jun2022_update4`

**Actual Behavior**

On running a 4 rank run of LJ on recent LAMMPS tags with ROCm, a runtime error reporting that atoms have been lost crashes the run.

**Steps to Reproduce**

Build either `stable_2Aug2023` or `patch_15Jun2023` with any version of ROCm 5.4.6 or higher. Run a 4-rank LJ, and you should observe the runtime error.

**Further Information, Files, and Links**
I've narrowed the exact issue down to https://github.com/lammps/lammps/commit/806af5322e2493d8c4a8ca725c574805bf093d84#diff-a1802f409f4544598478fccac3292204f8b61df03660be59a0340ae108f5ec22L770

Reverting the moving of that line fixes this issue. Alternatively, adding a guard such as:
`if (fpair->lmp->kokkos->neigh_thread) fpair->fuse_force_clear_flag = 1;`
to the moved line also fixes the issue.

Since multiple versions of ROCm show the runtime error, I think this is a logic bug.

**Comment by stanmoore1** [comment]
@IanBogle thanks for the bug report, will take a look

**Comment by stanmoore1** [comment]
@IanBogle it seems to run fine for me on MI250X with 4 ranks, not sure what is different

**Comment by IanBogle** [comment]
We've seen the issue on more recent versions of ROCm (5.7.0+) as well, so it could be some interplay between compiler/driver changes and code changes. Does applying the fix I outlined break anything for you?

**Comment by IanBogle** [comment]
Thinking about it more, I'm running on a relatively recent driver version, so it could be driver differences that expose the issue. As far as I know this change fixes it, so getting the change upstream ahead of time might avoid significant headaches on a future driver update (assuming that the change doesn't break anything for other configurations).

**Comment by stanmoore1** [comment]
@IanBogle the change in question above enables kernel fusion whenever using a `FULL` neighbor list. Reverting the change makes it so kernel fusion will only occur when using `neigh/thread yes` which is default for only 16k atoms or less, which could hurt performance. So the change was intentional. I have one idea that might help but I will need your help to test since I can't reproduce the issue on my end.

**Comment by IanBogle** [comment]
Sounds good, the issue is very easy for me to reproduce. Let me know what the change is, and I'll test it out.

**Comment by stanmoore1** [comment]
@IanBogle can you try the changes here: https://github.com/lammps/lammps/pull/3930/commits/e840d422efb937ab2bef3db0de971149a0bde4e5?

**Comment by IanBogle** [comment]
Building with that change results in a bunch of compilation errors of the form:
![image](https://github.com/lammps/lammps/assets/107126280/47511f78-528e-4226-8d99-febaf8092064)

It could rely on other changes I don't have, but I tried both the tags I've been using and the parent commit of the commit you linked and got the same errors.

**Comment by stanmoore1** [comment]
Sorry should be fixed with https://github.com/lammps/lammps/pull/3930/commits/c521d54f85c2aaef9e937cabbc19e60bb8154452.

**Comment by stanmoore1** [comment]
Running LJ with 4 NVIDIA V100 GPUs also runs fine with the original code.

**Comment by IanBogle** [comment]
Those changes do build, thanks!

No luck, the error still shows:
![image](https://github.com/lammps/lammps/assets/107126280/efff60fc-f80d-4177-be62-91653e715736)

**Comment by stanmoore1** [comment]
@IanBogle does the issue show on OLCF Frontier?

**Comment by IanBogle** [comment]
I'm not sure, I've been tracking it on an internal system. I'll check that.

**Comment by stanmoore1** [comment]
Thanks, it looks like Frontier is currently down. I will try too once it is back up. I think Frontier will be a good data point in narrowing down the issue...

**Comment by IanBogle** [comment]
Agreed. If we can reproduce somewhere that we can both see, it'll be very useful in resolving the issue. Though, I have a feeling this might only appear on systems only I can see.

My goal now is to narrow the issue down enough to ticket it internally, and try and get a more final resolution that way, rather than reverting the change that causes the symptom.

**Comment by stanmoore1** [comment]
@IanBogle I ran on OLCF Frontier and did not see any lost atoms. Please let me know if you see issues on Frontier and I will revisit, otherwise I think the issue may be specific to your internal machine.

**Comment by IanBogle** [comment]
I had suspected that would be the case. Could you point me to what files contain the kernel fusing code that the `fpair->fuse_force_clear_flag` triggers? I want to look into making a minimal reproducer, and that would help me get started.

**Comment by stanmoore1** [comment]
@IanBogle originally the force array was cleared in a separate kernel here:

https://github.com/lammps/lammps/blob/develop/src/KOKKOS/verlet_kokkos.cpp#L374
https://github.com/lammps/lammps/blob/develop/src/KOKKOS/verlet_kokkos.cpp#L528-L607

However, for a full neighbor list (only), the force clear kernel can be fused with the force compute kernel here:

https://github.com/lammps/lammps/blob/develop/src/KOKKOS/pair_kokkos.h#L140-L144

This reduces launch latency.

The conditions for the fusing are given here:

https://github.com/lammps/lammps/blob/develop/src/KOKKOS/verlet_kokkos.cpp#L610-L615

**Comment by IanBogle** [comment]
Great, thanks!

**Comment by akohlmey** [comment]
@IanBogle @stanmoore1 I have merged the collected KOKKOS package fixes to the develop branch. Is this issue still an open issue? Or is it - like the discussion seems to imply - isolated to a single machine setup and thus difficult to reproduce and address?

**Comment by stanmoore1** [comment]
@akohlmey I think we should close this for now. @IanBogle feel free to open another issue if necessary.
